### ISSUE TITLE
grSImのX座標がおかしい

### ISSUE THREAD

**Issue by asoyusaku** [Rione/ssl-RACOON-MW#26]
<img width="378" alt="2024-06-30_14 07 19" src="https://github.com/Rione/ssl-RACOON-MW/assets/131383591/246f6dbb-1706-423f-a328-a295dbae3287">

**Comment by Tamagoham** [comment]
grSimのSet Positionボタンからの位置設定は、少しずれてるかも知れない
手動で近くに持って行くと、Ｘ座標が1ケタ台になる
